### ISSUE TITLE
Is the name of the function incorrect?

### ISSUE THREAD

**Issue by cahlchang** [zk-phi/sky-color-clock#4]
I tried this extension, but it does not seem to work.
Looking at the source, I found something like misspelling,

https://github.com/zk-phi/sky-color-clock/blob/4dae171ab4712880219433b9382cb5e9aeddd475/sky-color-clock.el#L81

I modified "sky-color-clock-initialize-openweathermap-client".
Then I could see the weather from my emacs.
Thanks!

**Comment by zk-phi** [comment]
Fixed! Thanks for your report :)
